INSERT INTO tasks (title, description, task_date, is_completed)
VALUES
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-4', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-5', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-6', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-7', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-8', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-11', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-12', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-13', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-14', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-15', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-18', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-19', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-20', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-21', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-21', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-25', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-26', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-27', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-28', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-4-29', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-5-2', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-5-3', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-5-4', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-5-5', FALSE),
    ('Do a leetcode exercise', 'Practice required to keep mind sharp', '2022-5-6', FALSE),
    ('Finish Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-10', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-4', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-5', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-6', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-7', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-8', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-9', FALSE),
    ('Work on Quota', 'This Project needs to be completed to showcase my programming skills', '2022-4-10', FALSE);
